[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "bash"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'", "chmod +x start.sh"]

[start]
cmd = "bash start.sh"
